# Generated by Django 4.0.1 on 2022-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(default='placeholder string for the blurb', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
