# Generated by Django 4.0.1 on 2022-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_blurb_alter_book_author_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='blurb',
            field=models.TextField(max_length=1500),
        ),
    ]
